name: Rust Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests default
      run: cargo test --release --package bitcoin-explorer -- --test-threads=1 --show-output
    - name: Run tests no-default
      run: cargo test --release --no-default-features --package bitcoin-explorer -- --test-threads=1 --show-output
